export const storeInfo = {
  name: "StyleHub Myanmar",
  description:
    "Your ultimate destination for the latest fashion trends, stylish clothing, and trendy accessories",
  location: {
    address: "No. 123, Bogyoke Aung San Road, Pabedan Township",
    city: "Yangon",
    township: "Pabedan Township",
    country: "Myanmar",
    mapUrl: "https://maps.google.com/?q=Yangon",
  },
  hours: {
    weekdays: "9:00 AM - 9:00 PM",
    saturday: "9:00 AM - 10:00 PM",
    sunday: "10:00 AM - 8:00 PM",
  },
  contact: {
    phone: "+95 9 123 456 789",
    email: "info@stylehub-myanmar.com",
    facebook: "facebook.com/stylehubmm",
    viber: "+95 9 123 456 789",
  },
  policies: {
    shipping:
      "Free delivery for orders above 50,000 MMK within Yangon. Express delivery available.",
    returns:
      "Clothes can be returned within 7 days with tags attached. No returns on underwear or swimwear.",
    warranty:
      "Quality guaranteed. Please report any defects within 3 days of receiving your item.",
    payment:
      "We accept Cash on Delivery (COD), KBZ Pay, Wave Pay, and KPay.",
  },
};

export const categories = [
  { name: "Men's Clothing", icon: "👕", count: 5, slug: "mens-clothing" },
  { name: "Women's Clothing", icon: "👗", count: 6, slug: "womens-clothing" },
  { name: "Kids & Baby", icon: "👶", count: 3, slug: "kids-clothing" },
  { name: "Accessories", icon: "🕶️", count: 2, slug: "accessories" },
  { name: "Shoes", icon: "👟", count: 2, slug: "shoes" },
  { name: "Activewear", icon: "🏃", count: 1, slug: "activewear" },
];

export const products = [
  {
    id: "1",
    name: "Classic Men's White T-Shirt",
    name_my: "အမျိုးသားဝတ် တီရှပ်အဖြူရောင်",
    price: 15000,
    originalPrice: 20000,
    rating: 4.8,
    reviews: 120,
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&q=80&w=800",
    category: "mens-clothing",
    isNew: true,
    colors: ["White", "Black", "Navy"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "2",
    name: "Elegant Summer Floral Dress",
    name_my: "နွေရာသီဝတ် ပန်းပွင့်ဒီဇိုင်း ဂါဝန်",
    price: 35000,
    rating: 4.9,
    reviews: 432,
    image: "https://images.unsplash.com/photo-1572804013309-82a89b4344c4?auto=format&fit=crop&q=80&w=800",
    category: "womens-clothing",
    isBestSeller: true,
    colors: ["Red/White", "Blue/White"],
    sizes: ["S", "M", "L"],
  },
  {
    id: "3",
    name: "Men's Slim Fit Denim Jeans",
    name_my: "အမျိုးသားဝတ် ဂျင်းဘောင်းဘီရှည်",
    price: 45000,
    originalPrice: 50000,
    rating: 4.7,
    reviews: 89,
    image: "https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&q=80&w=800",
    category: "mens-clothing",
    colors: ["Light Blue", "Dark Blue", "Black"],
    sizes: ["28", "30", "32", "34", "36"],
  },
  {
    id: "4",
    name: "Women's Casual Blazer",
    name_my: "အမျိုးသမီးဝတ် ဘလေဇာအင်္ကျီ",
    price: 55000,
    rating: 4.6,
    reviews: 267,
    image: "https://images.unsplash.com/photo-1548624149-a2e6f461bd32?auto=format&fit=crop&q=80&w=800",
    category: "womens-clothing",
    colors: ["Beige", "Black", "Navy"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "5",
    name: "Kids Cotton Cartoon Pajamas",
    name_my: "ကလေးဝတ် ညအိပ်ဝတ်စုံ",
    price: 18000,
    originalPrice: 22000,
    rating: 4.9,
    reviews: 112,
    image: "https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?auto=format&fit=crop&q=80&w=800",
    category: "kids-clothing",
    isBestSeller: true,
    colors: ["Blue", "Pink", "Yellow"],
    sizes: ["2-3Y", "4-5Y", "6-7Y"],
  },
  {
    id: "6",
    name: "Unisex Canvas Sneakers",
    name_my: "ကျား/မ ဝတ် ကင်းဗတ်ဖိနပ်",
    price: 25000,
    rating: 4.8,
    reviews: 543,
    image: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&q=80&w=800",
    category: "shoes",
    isBestSeller: true,
    colors: ["White", "Black", "Red"],
    sizes: ["38", "39", "40", "41", "42", "43", "44"],
  },
  {
    id: "7",
    name: "Women's High-Waist Trousers",
    name_my: "အမျိုးသမီးဝတ် ခါးမြင့်ဘောင်းဘီ",
    price: 28000,
    originalPrice: 35000,
    rating: 4.9,
    reviews: 178,
    image: "https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&q=80&w=800",
    category: "womens-clothing",
    colors: ["Black", "Khaki", "Olive"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "8",
    name: "Men's Polo Shirt",
    name_my: "အမျိုးသားဝတ် ပိုလိုအင်္ကျီ",
    price: 20000,
    rating: 4.7,
    reviews: 234,
    image: "https://images.unsplash.com/photo-1581655353564-df123a1eb820?auto=format&fit=crop&q=80&w=800",
    category: "mens-clothing",
    colors: ["Navy", "White", "Grey"],
    sizes: ["M", "L", "XL", "XXL"],
  },
  {
    id: "9",
    name: "Leather Crossbody Bag",
    name_my: "သားရေလွယ်အိတ်",
    price: 45000,
    originalPrice: 55000,
    rating: 4.6,
    reviews: 145,
    image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&q=80&w=800",
    category: "accessories",
    colors: ["Brown", "Black"],
    sizes: ["One Size"],
  },
  {
    id: "10",
    name: "Women's Running Shoes",
    name_my: "အမျိုးသမီးဝတ် အားကစားဖိနပ်",
    price: 55000,
    rating: 4.8,
    reviews: 98,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&q=80&w=800",
    category: "shoes",
    isNew: true,
    colors: ["Pink", "Black", "Grey"],
    sizes: ["36", "37", "38", "39", "40"],
  },
  {
    id: "11",
    name: "Classic Aviator Sunglasses",
    name_my: "နေကာမျက်မှန်",
    price: 18000,
    rating: 4.7,
    reviews: 112,
    image: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&q=80&w=800",
    category: "accessories",
    colors: ["Gold", "Silver", "Black"],
    sizes: ["One Size"],
  },
  {
    id: "12",
    name: "Women's Oversized Sweater",
    name_my: "အမျိုးသမီးဝတ် ဆွယ်တာပွ",
    price: 32000,
    rating: 4.5,
    reviews: 567,
    image: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&q=80&w=800",
    category: "womens-clothing",
    isBestSeller: true,
    colors: ["Cream", "Grey", "Dusty Pink"],
    sizes: ["S", "M", "L"],
  },
  {
    id: "13",
    name: "Men's Casual Chinos",
    name_my: "အမျိုးသားဝတ် ချီနိုဘောင်းဘီ",
    price: 35000,
    originalPrice: 42000,
    rating: 4.6,
    reviews: 189,
    image: "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&q=80&w=800",
    category: "mens-clothing",
    colors: ["Khaki", "Navy", "Olive"],
    sizes: ["30", "32", "34", "36"],
  },
  {
    id: "14",
    name: "Women's Active Yoga Pants",
    name_my: "အမျိုးသမီးဝတ် ယောဂဘောင်းဘီ",
    price: 24000,
    originalPrice: 30000,
    rating: 4.8,
    reviews: 76,
    image: "https://images.unsplash.com/photo-1518310383802-640c2de311b2?auto=format&fit=crop&q=80&w=800",
    category: "activewear",
    isNew: true,
    colors: ["Black", "Grey", "Maroon"],
    sizes: ["XS", "S", "M", "L"],
  },
  {
    id: "15",
    name: "Kids Denim Jacket",
    name_my: "ကလေးဝတ် ဂျင်းဂျာကင်",
    price: 26000,
    rating: 4.7,
    reviews: 345,
    image: "https://images.unsplash.com/photo-1514316454349-750a7fd3da3a?auto=format&fit=crop&q=80&w=800",
    category: "kids-clothing",
    colors: ["Blue Denim"],
    sizes: ["3-4Y", "5-6Y", "7-8Y"],
  },
  {
    id: "16",
    name: "Men's Hooded Sweatshirt",
    name_my: "အမျိုးသားဝတ် ခေါင်းစွပ်ဆွယ်တာ",
    price: 28000,
    rating: 4.5,
    reviews: 870,
    image: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&q=80&w=800",
    category: "mens-clothing",
    colors: ["Grey", "Black", "Navy"],
    sizes: ["M", "L", "XL", "XXL"],
  },
  {
    id: "17",
    name: "Women's Pleated Midi Skirt",
    name_my: "အမျိုးသမီးဝတ် စကတ်အရှည်",
    price: 22000,
    originalPrice: 28000,
    rating: 4.8,
    reviews: 231,
    image: "https://images.unsplash.com/photo-1583496661160-c588c443c98d?auto=format&fit=crop&q=80&w=800",
    category: "womens-clothing",
    isNew: true,
    colors: ["Black", "Beige", "Green"],
    sizes: ["S", "M", "L"],
  },
  {
    id: "18",
    name: "Baby Romper Set",
    name_my: "ကလေးငယ်ဝတ် ဝမ်းဆက်",
    price: 15000,
    rating: 4.9,
    reviews: 45,
    image: "https://images.unsplash.com/photo-1519689680058-324335c77eba?auto=format&fit=crop&q=80&w=800",
    category: "kids-clothing",
    colors: ["White", "Mint", "Yellow"],
    sizes: ["0-3M", "3-6M", "6-12M"],
  },
  {
    id: "19",
    name: "Women's Silk Blouse",
    name_my: "အမျိုးသမီးဝတ် ပိုးသားအင်္ကျီ",
    price: 35000,
    rating: 4.8,
    reviews: 156,
    image: "https://images.unsplash.com/photo-1604928141064-207cea6f5722?auto=format&fit=crop&q=80&w=800",
    category: "womens-clothing",
    isNew: true,
    colors: ["Champagne", "Black", "Emerald"],
    sizes: ["S", "M", "L"],
  },
];
