export const categories = [
  { name: "Laptops", icon: "💻", count: 2, slug: "laptops" },
  { name: "Smartphones", icon: "📱", count: 2, slug: "smartphones" },
  { name: "Audio", icon: "🎧", count: 2, slug: "audio" },
  { name: "Accessories", icon: "⌨️", count: 9, slug: "accessories" },
  { name: "Smart Home", icon: "🏠", count: 2, slug: "smart-home" },
  { name: "Gaming", icon: "🎮", count: 1, slug: "gaming" },
];

export const products = [
  {
    id: "1",
    name: "Premium Wireless Headphones with Active Noise Cancellation",
    price: 627900,
    originalPrice: 837900,
    rating: 4.8,
    reviews: 234,
    image: "/wireless-headphones.png",
    category: "audio",
    isNew: true,
  },
  {
    id: "2",
    name: "4K Ultra HD Smart Monitor 32 inch",
    price: 1152900,
    rating: 4.9,
    reviews: 189,
    image: "/4k-monitor.jpg",
    category: "accessories",
    isNew: true,
  },
  {
    id: "3",
    name: "Mechanical Gaming Keyboard RGB",
    price: 312900,
    originalPrice: 417900,
    rating: 4.7,
    reviews: 456,
    image: "/gaming-keyboard.png",
    category: "gaming",
    isNew: true,
  },
  {
    id: "4",
    name: "Portable SSD 2TB External Storage",
    price: 522900,
    rating: 4.9,
    reviews: 312,
    image: "/portable-ssd.jpg",
    category: "accessories",
    isNew: true,
  },
  {
    id: "5",
    name: "Wireless Mouse Ergonomic Design",
    price: 165900,
    originalPrice: 207900,
    rating: 4.6,
    reviews: 567,
    image: "/wireless-mouse.png",
    category: "accessories",
    isNew: true,
  },
  {
    id: "6",
    name: "USB-C Hub Multiport Adapter",
    price: 123900,
    rating: 4.7,
    reviews: 423,
    image: "/usb-hub.png",
    category: "accessories",
    isNew: true,
  },
  {
    id: "7",
    name: "Smartphone Stand Adjustable Aluminum",
    price: 60900,
    originalPrice: 81900,
    rating: 4.5,
    reviews: 891,
    image: "/phone-stand.jpg",
    category: "accessories",
    isNew: true,
  },
  {
    id: "8",
    name: "Webcam 4K Ultra HD with Microphone",
    price: 270900,
    rating: 4.8,
    reviews: 278,
    image: "/webcam-4k.jpg",
    category: "accessories",
    isNew: true,
  },
  {
    id: "9",
    name: "Laptop Stand Aluminum Portable",
    price: 102900,
    rating: 4.9,
    reviews: 1234,
    image: "/laptop-stand.png",
    category: "accessories",
    isBestSeller: true,
  },
  {
    id: "10",
    name: "Smart Watch Fitness Tracker",
    price: 417900,
    originalPrice: 522900,
    rating: 4.7,
    reviews: 892,
    image: "/modern-smartwatch.png",
    category: "accessories",
    isBestSeller: true,
  },
  {
    id: "11",
    name: "Bluetooth Speaker Waterproof",
    price: 186900,
    rating: 4.8,
    reviews: 623,
    image: "/bluetooth-speaker.jpg",
    category: "audio",
    isBestSeller: true,
  },
  {
    id: "12",
    name: "Graphics Tablet for Designers",
    price: 375900,
    originalPrice: 480900,
    rating: 4.9,
    reviews: 445,
    image: "/graphics-tablet.png",
    category: "accessories",
    isBestSeller: true,
  },
  {
    id: "13",
    name: "Ultra Slim Laptop 14-inch Pro",
    price: 2599000,
    originalPrice: 2899000,
    rating: 4.9,
    reviews: 156,
    image: "/surface.jpg",
    category: "laptops",
    isNew: true,
  },
  {
    id: "14",
    name: "Gaming Laptop RTX 4060",
    price: 3150000,
    rating: 4.8,
    reviews: 89,
    image: "/asus.jpg",
    category: "laptops",
  },
  {
    id: "15",
    name: "Flagship Smartphone 5G 256GB",
    price: 1899000,
    originalPrice: 2100000,
    rating: 4.9,
    reviews: 342,
    image: "/iphone14.jpg",
    category: "smartphones",
    isBestSeller: true,
  },
  {
    id: "16",
    name: "Mid-Range Camera Phone",
    price: 850000,
    rating: 4.6,
    reviews: 124,
    image: "/iphonex.jpg",
    category: "smartphones",
  },
  {
    id: "17",
    name: "Smart LED Bulb RGB Color",
    price: 35000,
    rating: 4.5,
    reviews: 456,
    image: "/smartled.jpg",
    category: "smart-home",
  },
  {
    id: "18",
    name: "Smart Security Camera 1080p",
    price: 125000,
    originalPrice: 150000,
    rating: 4.7,
    reviews: 231,
    image: "/smartcamera.jpg",
    category: "smart-home",
    isNew: true,
  },
];
