export const storeInfo = {
  name: "MediCare Pharmacy",
  description:
    "Your trusted source for quality healthcare products, medicines, and medical equipment",
  location: {
    address: "No. 456, Pyay Road, Kamayut Township",
    city: "Yangon",
    township: "Kamayut Township",
    country: "Myanmar",
    mapUrl: "https://maps.google.com/?q=MediCare+Pharmacy+Yangon",
  },
  hours: {
    weekdays: "8:00 AM - 10:00 PM",
    saturday: "8:00 AM - 10:00 PM",
    sunday: "9:00 AM - 9:00 PM",
  },
  contact: {
    phone: "+95 9 987 654 321",
    email: "info@medicare-myanmar.com",
    facebook: "facebook.com/medicaremm",
    viber: "+95 9 987 654 321",
  },
  policies: {
    shipping:
      "Free delivery for medical supplies above 50,000 MMK within Yangon. Express 2-hour delivery available for urgent prescriptions.",
    returns:
      "Medicine returns are accepted within 24 hours only if the seal is unbroken. Medical equipment has a 7-day return policy.",
    warranty:
      "Electronic medical devices come with a 1-year service warranty. Digital thermometers have a 6-month warranty.",
    payment:
      "We accept Cash on Delivery (COD), KBZ Pay, Wave Pay, and KPay.",
  },
};

export const categories = [
  { name: "Prescription", icon: "💊", count: 1, slug: "prescription" },
  { name: "OTC Medicine", icon: "🌡️", count: 3, slug: "otc-medicine" },
  { name: "Vitamins", icon: "🍊", count: 3, slug: "vitamins" },
  { name: "First Aid", icon: "🩹", count: 5, slug: "first-aid" },
  { name: "Medical Gear", icon: "🩺", count: 6, slug: "medical-gear" },
  { name: "Baby Care", icon: "🍼", count: 1, slug: "baby-care" },
];

export const products = [
  {
    id: "1",
    name: "Paracetamol 500mg (10 Tabs)",
    name_my: "ပါရာစီတမော ၅၀၀ မီလီဂရမ် (၁၀ လုံးပါ)",
    price: 1500,
    originalPrice: 2000,
    rating: 4.9,
    reviews: 1250,
    image: "https://www.stelonbiotech.com/wp-content/uploads/2022/04/PYREMUST-650-TAB.jpg",
    category: "otc-medicine",
    isNew: true,
  },
  {
    id: "2",
    name: "Digital Blood Pressure Monitor",
    name_my: "ဒီဂျစ်တယ် သွေးပေါင်ချိန်စက်",
    price: 65000,
    rating: 4.8,
    reviews: 432,
    image: "https://m.media-amazon.com/images/I/715LHO9x+tL._AC_UF1000,1000_QL80_.jpg",
    category: "medical-gear",
    isBestSeller: true,
  },
  {
    id: "3",
    name: "Vitamin C 1000mg Effervescent",
    name_my: "ဗီတာမင်စီ ၁၀၀၀ မီလီဂရမ် ရေဖျော်သောက်ဆေး",
    price: 12000,
    originalPrice: 15000,
    rating: 4.7,
    reviews: 890,
    image: "https://ozhealth.com.sg/cdn/shop/files/naturesaid-vitaminc-effervescent-1_grande.jpg?v=1721357291",
    category: "vitamins",
    isNew: true,
  },
  {
    id: "4",
    name: "Infrared Forehead Thermometer",
    name_my: "အနီအောက်ရောင်ခြည်သုံး နဖူးတိုင်း အပူချိန်တိုင်းကိရိယာ",
    price: 35000,
    rating: 4.6,
    reviews: 267,
    image: "https://static.vecteezy.com/system/resources/previews/060/930/910/large_2x/a-thermometer-with-a-red-light-on-it-photo.jpg",
    category: "medical-gear",
  },
  {
    id: "5",
    name: "First Aid Kit (Essential)",
    name_my: "ရှေးဦးသူနာပြုသေတ္တာ (အခြေခံ)",
    price: 25000,
    originalPrice: 30000,
    rating: 4.9,
    reviews: 112,
    image: "https://m.media-amazon.com/images/I/71EKBDVCx0L._AC_UF894,1000_QL80_.jpg",
    category: "first-aid",
    isBestSeller: true,
  },
  {
    id: "6",
    name: "N95 Medical Face Mask (Box of 20)",
    name_my: "N95 ဆေးဘက်ဆိုင်ရာ နှာခေါင်းစည်း (အခု ၂၀ ပါ)",
    price: 18000,
    rating: 4.8,
    reviews: 543,
    image: "https://m.media-amazon.com/images/I/81Ox3n9GsZL._AC_SL1500_.jpg",
    category: "first-aid",
    isBestSeller: true,
  },
  {
    id: "7",
    name: "Baby Multivitamin Syrup 100ml",
    name_my: "ကလေးအားဆေးရည် ၁၀၀ မီလီလီတာ",
    price: 8500,
    originalPrice: 10000,
    rating: 4.9,
    reviews: 178,
    image: "https://m.media-amazon.com/images/I/71aEG6KiYYL._AC_SL1500_.jpg",
    category: "baby-care",
  },
  {
    id: "8",
    name: "Hand Sanitizer Gel 500ml",
    name_my: "လက်သန့်ဆေးရည် ၅၀၀ မီလီလီတာ",
    price: 5500,
    rating: 4.7,
    reviews: 2340,
    image: "https://media.nedigital.sg/fairprice/fpol/media/images/product/XL/12110581_XL1_20220620.jpg",
    category: "otc-medicine",
  },
  {
    id: "9",
    name: "Antiseptic Liquid 250ml",
    name_my: "ပိုးသတ်ဆေးရည် ၂၅၀ မီလီလီတာ",
    price: 6500,
    originalPrice: 7500,
    rating: 4.6,
    reviews: 145,
    image: "https://singaporesoap.com/wp-content/uploads/2021/05/Bactiq-Hand-Sanitiser-5-Litre-Bulk-Refill-600x600.jpg",
    category: "first-aid",
  },
  {
    id: "10",
    name: "Omega-3 Fish Oil 1000mg (60 Caps)",
    name_my: "အိုမီဂါ-၃ ငါးကြီးဆီ (လုံးရေ ၆၀ ပါ)",
    price: 28000,
    rating: 4.8,
    reviews: 980,
    image: "https://m.media-amazon.com/images/I/61NwoknrKrL.jpg",
    category: "vitamins",
    isNew: true,
  },
  {
    id: "11",
    name: "Pulse Oximeter",
    name_my: "လက်ချောင်းထိပ်သွေးတွင်းအောက်ဆီဂျင်တိုင်းစက်",
    price: 22000,
    rating: 4.7,
    reviews: 1120,
    image: "https://ecdn6.globalso.com/upload/p/624/image_product/2024-06/66612d609fd9c18519.jpg",
    category: "medical-gear",
  },
  {
    id: "12",
    name: "Adhesive Bandages (100 Pack)",
    name_my: "ပလာစတာ (၁၀၀ ပါ)",
    price: 4500,
    rating: 4.5,
    reviews: 5670,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmeSi3kWQIeunCjHnn5z3RQQZc25Mv6UAsWA&s",
    category: "first-aid",
    isBestSeller: true,
  },
  {
    id: "13",
    name: "Cough Syrup (Sugar Free) 100ml",
    name_my: "ချောင်းဆိုးပျောက်ဆေးရည် (သကြားမပါ) ၁၀၀ မီလီလီတာ",
    price: 4500,
    originalPrice: 5500,
    rating: 4.6,
    reviews: 189,
    image: "https://cmhlprodblobstorage1.blob.core.windows.net/sys-master-cmhlprodblobstorage1/he8/he0/8975081177118/cmhl_1000000002229_1_hero.jpg_Default-WorkingFormat_1000Wx1000H",
    category: "otc-medicine",
  },
  {
    id: "14",
    name: "Nebulizer Machine",
    name_my: "ရှူဆေးစက်",
    price: 85000,
    originalPrice: 95000,
    rating: 4.8,
    reviews: 76,
    image: "https://img.lazcdn.com/g/shop/9ad4e9dea6681d0df563ae3c1dc7d941.jpeg_960x960q80.jpg_.webp",
    category: "medical-gear",
    isNew: true,
  },
  {
    id: "15",
    name: "Digital Thermometer",
    name_my: "ဒီဂျစ်တယ် အပူချိန်တိုင်းကိရိယာ",
    price: 5500,
    rating: 4.7,
    reviews: 3450,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOrL8HWKoaJtyeXJuwKBtoBv_Tb7mQhW_jeg&s",
    category: "medical-gear",
  },
  {
    id: "16",
    name: "Alcohol Swabs (100pcs)",
    name_my: "အယ်လ်ကိုဟောဂွမ်းစ (၁၀၀ ခုပါ)",
    price: 3500,
    rating: 4.5,
    reviews: 870,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRoL6zS2sSUlBNUsqpHVQkSbdex69FEaJbUuA&s",
    category: "first-aid",
  },
  {
    id: "17",
    name: "Zinc Supplement 50mg (30 Tabs)",
    name_my: "ဇင့် (သွပ်ဓာတ်) အားဆေး (အလုံး ၃၀ ပါ)",
    price: 15000,
    originalPrice: 18000,
    rating: 4.8,
    reviews: 231,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjmCq8cNi3x1RaVxlfOd9qdViH-dRwykQh2w&s",
    category: "vitamins",
    isNew: true,
  },
  {
    id: "18",
    name: "Wheelchair (Foldable)",
    name_my: "Wheelchair",
    price: 250000,
    rating: 4.9,
    reviews: 45,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcScq3hkHTL29kGXgXctuqcL80fN1PqWO_fTaQ&s",
    category: "medical-gear",
  },
  {
    id: "19",
    name: "Amoxicillin 500mg (Prescription Only)",
    name_my: "အမောက်ဆိုဆီလင် ၅၀၀ မီလီဂရမ်",
    price: 3500,
    rating: 4.8,
    reviews: 156,
    image: "https://haloiv.com/wp-content/uploads/2024/06/amoxicillin-capsules-500mg-x21.jpg",
    category: "prescription",
    isNew: true,
  },
];
